"""Add ServerConfig

Revision ID: 4714839497ce
Revises: 920a401e8df6
Create Date: 2021-08-12 19:30:29.304975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4714839497ce'
down_revision = '920a401e8df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_configs',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('votelog_channel', sa.Integer(), nullable=True),
    sa.Column('confession_channel', sa.Integer(), nullable=True),
    sa.Column('admin_roles', sa.JSON(), nullable=True),
    sa.Column('minimum_vote', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_configs')
    # ### end Alembic commands ###
