"""Add cooldown

Revision ID: d55681f39187
Revises: 4714839497ce
Create Date: 2021-09-10 20:02:31.788236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d55681f39187"
down_revision = "4714839497ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server_configs",
        sa.Column("cooldown_time", sa.Integer(), nullable=True, default=0),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server_configs", "cooldown_time")
    # ### end Alembic commands ###
